@echo off
echo Starting Stock Recommendation System...

echo Starting Next.js application...
start cmd /k "npm install && npm run dev"

echo Service is starting. Please wait...
echo Application will be available at: http://localhost:3000 